- CHANGELOG.MD
- lib/ACF/PageGroup.php
- lib/BlocksController.php
Enable map component & block
TMS-679
> TMS-679: Enable map layout & block

- assets/styles/ui-components/_archive-filters.scss
> TMS-665: Color fix

- CHANGELOG.MD
- lib/ACF/Fields/ContactsFields.php
- lib/Integrations/Tampere/ApiController.php
Load choices with ajax
TMS-223
> TMS-223: Load choices with ajax

- partials/blocks/block-material.dust
> TMS-685-2: Fix material button text escape

- CHANGELOG.MD
- lib/ACF/ApplyMethodGroup.php
- lib/Localization.php
- lib/Taxonomy/ApplyMethod.php
- models/page-program.php
- partials/page-program.dust
> TMS-801: Add ApplyType tax

- CHANGELOG.MD
- lib/PostType/Project.php
- lib/Taxonomy/Portfolio.php
Added Project CPT and Portfolio taxonomy #63
TMS-737
Local, stage.
> TMS-737: Project CPT and Portfolio taxonomy

- CHANGELOG.MD
- lib/Formatters/ImageFormatter.php
- partials/layouts/layout-call-to-action.dust
- partials/layouts/layout-content-columns.dust
- partials/ui/image/image-meta-minimal.dust
> TMS-816: Unify image meta

- CHANGELOG.MD
- lib/ACF/Fields/ContactsFields.php
- lib/Formatters/ContactFormatter.php
- lib/Integrations/Tampere/ApiController.php
- lib/Integrations/Tampere/PersonApiController.php
- lib/Integrations/Tampere/PersonFacade.php
- lib/Integrations/Tampere/PlaceOfBusinessFacade.php
> TMS-817: Display API contacts

- CHANGELOG.MD
- lib/BlocksController.php
Remove Grid & Acc icons blocks from Post
TMS-664
> TMS-664: Remove Grid & Acc icons blocks from Post

- CHANGELOG.MD
- lib/Integrations/Tampere/ApiController.php
- models/page-contacts.php
Separate API url for English requests
TMS-810
> TMS-810: Separate url for English requests

- CHANGELOG.MD
- lib/ACF/Fields/EventsFields.php
Remove EventFields sort field
TMS-823
> TMS-823: Remove EventFields sort field

- CHANGELOG.MD
- lib/ACF/ProgramGroup.php
- partials/views/single-program/hero.dust
Add option to hide single program Apply info
TMS-832
> TMS-832: Add option to hide single program Apply info #83

- CHANGELOG.MD
- lib/ACF/ProgramGroup.php
- partials/views/single-program/info.dust
Double the program price character limit & hyphenate program info
TMS-833
> TMS-833: Double the program price character limit & hyphenate program info

- CHANGELOG.MD
- lib/Integrations/Tampere/ApiController.php
- lib/Integrations/Tampere/PersonApiController.php
Tampere API Performance optimizations
TMS-836
> TMS-836: Tampere API Performance optimizations

- CHANGELOG.MD
- assets/styles/ui-components/header/_primary-nav.scss
- models/shared/header.php
Disable navigation top level parent links
TMS-838
> TMS-838: Disable navigation top level parent links

- CHANGELOG.MD
- assets/styles/settings/brand/_typography.scss
- lib/Formatters/ContactFormatter.php
- partials/blocks/block-contacts.dust
Change contacts block & layout alignment 
TMS-834, 835
> TMS-834: Change contacts block & layout alignment

- CHANGELOG.MD
- lib/Integrations/Tampere/ApiController.php
CR: https://geniemdev.atlassian.net/browse/TMS-847
> TMS-847: Prevent double slashes on api url

- CHANGELOG.MD
- assets/styles/ui-components/_entry.scss
- assets/styles/ui-components/index.scss
- assets/styles/views/_page-program.scss
- assets/styles/views/_page.scss
- lib/ACF/PageProgramGroup.php
- lib/Integrations/Tampere/ApiController.php
- partials/page-program.dust
Convert PageProgram textarea to wysiwyg
TMS-859
> TMS-859: Convert PageProgram textarea to wysiwyg

- CHANGELOG.MD
- lib/PostType/Project.php
- lib/Roles.php
Setup user roles & permissions
TMS-705
> TMS-705: Setup user roles

- lib/Formatters/ContactFormatter.php
> Use importer plugin

- CHANGELOG.MD
- lib/ACF/Fields/Settings/HeaderSettingsTab.php
- lib/ThemeSupports.php
Add favicon to settings
TMS-807
> TMS-807: Add Favicon to settings

- CHANGELOG.MD
- lib/Traits/Breadcrumbs.php
Add separator icons to page breadcrumbs
TMS-872
> TMS-872: Add icons to to breadcrumbs

- assets/styles/ui-components/_entry.scss
- assets/styles/views/_single-post.scss
- assets/styles/views/index.scss
- models/single.php
- partials/single.dust
Improve drupal news support
TMS-881
> TMS-881: Improve drupal news support

- CHANGELOG.MD
- lib/ACF/ProjectGroup.php
- partials/views/single-project/sidebar.dust
Fix field name conflict
TMS-882
> TMS-882: Fix field name conflict

- CHANGELOG.MD
- models/search.php
Allow DialTredu & TreduEvent cpts in search
TMS-855
> TMS-855: Allow cpts in search

- CHANGELOG.MD
- lib/Formatters/TreduEventsFormatter.php
CR: https://geniemdev.atlassian.net/browse/TMS-893
> TMS-893: Fix Tredu events order

- CHANGELOG.MD
- lib/ACF/Fields/Settings/ChatTab.php
- lib/ACF/SettingsGroup.php
- models/shared/header.php
- partials/shared/header.dust
CR: https://geniemdev.atlassian.net/browse/TMS-891
> TMS-891: Add chat

- CHANGELOG.MD
- lib/BlocksController.php
Allow PlaceOfBusiness block in Program CPT
TMS-883
> TMS-883: Allow PlaceOfBusiness block in Program CPT

- CHANGELOG.MD
- models/page-contacts.php
> PIEN-7508: fix drupal contacts on contact page template

- CHANGELOG.MD
- lib/EmbedController.php
- lib/ThemeController.php
Add play.quickchannel.com embed support
TMS-910
> TMS-910: Add play.quickchannel.com embed support

- CHANGELOG.MD
- partials/views/home/home-highlight.dust
CR: https://geniemdev.atlassian.net/browse/PIEN-7610
> PIEN-7610: Fix showing images in highlight block

- CHANGELOG.MD
- lib/ACF/Fields/VideoFields.php
- lib/ACF/FrontPageGroup.php
- lib/ACF/Layouts/VideoLayout.php
- lib/ACF/OnepagerGroup.php
- lib/ACF/PageGroup.php
- partials/blocks/block-video.dust
- partials/layouts/layout-video.dust
Add video component & block video align option
TMS-897
> TMS-897: Add video component & block video align option

- CHANGELOG.MD
- lib/Formatters/ContactFormatter.php
> TMS-916: Fix order of selected api contacts.

- CHANGELOG.MD
- lib/Formatters/SubpagesFormatter.php
- style.css
Task: https://geniemdev.atlassian.net/browse/PIEN-8045
> PIEN-8045: Change subpage-block to work with all post types that use it

- CHANGELOG.MD
- lib/CronJobs.php
- lib/Expirator.php
- lib/ThemeController.php
Task: https://geniemdev.atlassian.net/browse/TMS-902
Add cron-job to modify past TreduEvent CPTs as drafts
> TMS-902: Add cron-job to modify past events as drafts

- CHANGELOG.MD
- lib/ThemeSupports.php
CR: https://geniemdev.atlassian.net/browse/PIEN-8439
Add pageId meta tag to head for Siteimprove hotlinking
> PIEN-8439: Add pageID meta tag

- CHANGELOG.MD
- models/single.php
- partials/views/single/single-related.dust
CR: https://geniemdev.atlassian.net/browse/PIEN-8524
Display API image
PIEN-8524
> PIEN-8524: Display API image

- CHANGELOG.MD
- lib/Blocks/LinkListBlock.php
CR: https://geniemdev.atlassian.net/browse/PIEN-8585
Check empty links
PIEN-8585
> PIEN-8585: Check empty links

- CHANGELOG.MD
- models/single.php
CR: https://geniemdev.atlassian.net/browse/PIEN-8394
Add API image to og:image tag.
PIEN-8394
> PIEN-8394: Add API image to og:image tag

- CHANGELOG.MD
- lib/ACF/PageProjectGroup.php
- partials/page-project.dust
CR: https://hiondigital.atlassian.net/browse/TMS-926
- Add components & blocks to projects-page layout
- Add components to use in projects-page
> TMS-926: Add components & blocks to projects-page

- CHANGELOG.MD
- assets/styles/views/_page-project.scss
- style.css
Severa-ID: 2108
Severa-kuvaus: TMS-995 Tredun omien tapahtumien listauksessa Projektit-sivulla ei näy nostoissa kuvat
Task: https://hiondigital.atlassian.net/browse/TMS-995
Show project-listing component images in projects-page
> TMS-995: Show project images in projects-page

- CHANGELOG.MD
- lib/ACF/Fields/CallToActionFields.php
- lib/ACF/Fields/ContentColumnsFields.php
- lib/ACF/Fields/GridFields.php
- lib/ACF/Fields/TextBlockFields.php
- style.css
Severa-kuvaus: TMS-980 Pohjateeman komponenttien sisällön lisääminen sivuston hakutuloksiin
Task: https://hiondigital.atlassian.net/browse/TMS-980
Add redipress_include_search to components
> TMS-980: Add redipress_include_search to components

- CHANGELOG.MD
- partials/shared/header-inner.dust
- partials/ui/menu/language-nav.dust
- style.css
Severa-kuvaus: TMS-1015 Saavutettavuuskorjauksia
Task: https://hiondigital.atlassian.net/browse/TMS-1015
Fix duplicate ID for horizontal language navigation
> TMS-1015: Header accessibility fixes

- CHANGELOG.MD
- partials/blocks/block-contacts.dust
- partials/layouts/layout-contacts.dust
Severa-ID: 2108
Severa-kuvaus: TMS-1029 Yhteystietojen kuvakokojen muutos
Task: https://hiondigital.atlassian.net/browse/TMS-1029
Change contacts-blocks width
> TMS-1029: Change contacts-blocks width

- CHANGELOG.MD
- lib/ACF/ContactGroup.php
- models/search.php
Severa-ID: 2108
Severa-kuvaus: TMS-1075 Redipress 2 päivitys
Task: https://hiondigital.atlassian.net/browse/TMS-1075
Filter changes for Redipress 2 update
> TMS-1075: Redipress 2 filters

- CHANGELOG.MD
- lib/Expirator.php
Severa-ID: 2132
Severa-kuvaus: TMS-1075 Redipress 2 päivitys
Task: https://hiondigital.atlassian.net/browse/TMS-1075
Fixes expirator bug.
> TMS-1075-expirator: Fix expirator bug

- CHANGELOG.MD
- lib/ACF/ProgramGroup.php
Severa-kuvaus: TMS-1088 Tredun koulutushaussa ei toimi "Näytä vain haussa olevat" hakusanalla
Task: https://hiondigital.atlassian.net/browse/TMS-1088
> TMS-1088: Change program dates to be queryable by redipress

- CHANGELOG.MD
- lib/ACF/Fields/CallToActionFields.php
- lib/ACF/Fields/ContentColumnsFields.php
Severa-ID: 2108
Severa-kuvaus: TMS-1109 Lihavointi ja kursivointi mahdolliseksi kolmeen komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-TMS-1109
Change content-columns (Palstat) & call-to-action (Manuaaliset nostot) components TextAreas to Wysiwyg-fields
> TMS-1109: Change ContentColumns & CallToAction TextArea fields to Wysiwyg

- CHANGELOG.MD
- partials/page-project.dust
- partials/views/page-project/filters.dust
- partials/views/single-project/sidebar.dust
Severa-ID: 2132
Severa-kuvaus: TMS-1125 Muutos projektilistan hakuun ja projektisivuun
Task: https://hiondigital.atlassian.net/browse/TMS-1125
Remove portfolio (Salkku) filters & info from front-end
> TMS-1125: Remove portfolio filters & info from front-end

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
Severa-kuvaus: TMS-1151 Saavutettavuus: Näppäimistökohdennuksessa ei värin vaihtumista pitäisi olla
Task: https://hiondigital.atlassian.net/browse/TMS-1151
Change hero-links focus-styles to be more visible
> TMS-1151: Change hero-links focus-styles

- CHANGELOG.MD
- assets/styles/ui-components/_pagination.scss
- partials/shared/header-logo.dust
Severa-kuvaus: TMS-1149 Saavutettavuus: Puutteellinen näkyvä kohdistus
Task: https://hiondigital.atlassian.net/browse/TMS-1149
- Fix focus styles to be more visible
- Add padding for header-logo to prevent focus-styles from going over links next to the logo
> TMS-1149: Accessibility fixes for focus-styles

- CHANGELOG.MD
- assets/styles/base/_base.scss
- partials/blocks/block-grid-item--featured.dust
Severa-kuvaus: TMS-1148 Saavutettavuus: Responsiivisuusongelmia Tredu.fi
Task: https://hiondigital.atlassian.net/browse/TMS-1148
- Decrease html min-width to support scaling for zoomed-in browsers
- Decrease small display padding for grid-item to prevent content overflow on zoomed-in view
> TMS-1148: Responsiveness fixes for zoomed in browsers

- CHANGELOG.MD
- partials/ui/menu/menu-item-single.dust
Severa-kuvaus: TMS-1144 Saavutettavuus: etusivun aria-attribuutti
Task: https://hiondigital.atlassian.net/browse/TMS-1144
Change correct aria-attribute for breadcrumbs menu-item
> TMS-1144: Change aria-attribute for menu-item

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.MD
- lib/ACF/Fields/VideoFields.php
- partials/blocks/block-video.dust
Projekti: Tampereen kaupunki, konsernihallinto / Tietohallintoyksikkö: Tampere multisite support
Tiketin kuvaus: TMS-1201 Uusi Quickchannel-alusta sallituksi videolohkoon ja -komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-1201
Add new field for video-component that enables an iframe-video to be embedded.
> TMS-1201: Add iframe-field for video fields
